networks:
  sdrserver:
    driver: bridge

services:
  #
  # Traefik
  sdrserver-traefik:
    image: traefik:v3.3.6
    container_name: sdrserver-traefik
    restart: unless-stopped
    networks:
      - sdrserver
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
  #
  # Glances
  sdrserver-glances:
    image: nicolargo/glances:latest
    container_name: sdrserver-glances
    restart: unless-stopped
    pid: host
    networks:
      - sdrserver
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      # Default
      - traefik.http.services.sdrserver-glances.loadbalancer.server.port=61208
      - traefik.http.routers.sdrserver-glances.service=sdrserver-glances
      - traefik.http.routers.sdrserver-glances.entrypoints=web
      - traefik.http.routers.sdrserver-glances.rule=Host(`glances.sdrserver.localhost`)
  #
  # AirSpy Server
  sdrserver-airspy:
    build:
      context: ./docker/airspy/build
      dockerfile: Dockerfile
      args:
        AIRSPY_TARGET_PLATFORM: ${AIRSPY_TARGET_PLATFORM}
    container_name: sdrserver-airspy
    restart: unless-stopped
    privileged: true
    networks:
      - sdrserver
    ports:
      - 5555:5555
    volumes:
      - ./docker/airspy/data:/airspy/data
    devices:
      - /dev/bus/usb:/dev/bus/usb
